export const ADD_TODO = 'ADD_TODO'
export const FETCH_TODOS = 'FETCH_TODOS'
export const REMOVE_TODO = 'REMOVE_TODO'
export const RENAME_TODO = 'RENAME_TODO'
export const COMPLETED_TODO = 'COMPLETED_TODO'